version: '3.4'

networks:
  nosblowa-dev:
    driver: bridge

services:
  nosblowa:
    image: nosblowa:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=usersdb;username=nosblowa;password=1234"
    networks:
      - nosblowa-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "nosblowa"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "usersdb"
    networks:
      - nosblowa-dev
volumes:
  db_volume:
         
